[versions]
# libraries
javaTarget = "17"
# the highest version supported by the plugin at the moment
kotlin = "2.3.21"
xemanticKotlinTest = "1.17.5"
kotlinSemver = "3.1.0"
# plugins
versionCatalogUpdatePlugin = "1.1.0"
dokkaPlugin = "2.2.0"
jreleaserPlugin = "1.25.0"
binaryCompatibilityValidatorPlugin = "0.18.1"
mavenPublishPlugin = "0.37.0"
xemanticConventionsPlugin = "0.6.8"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
xemantic-kotlin-test = { module = "com.xemantic.kotlin:xemantic-kotlin-test", version.ref = "xemanticKotlinTest" }
kotlin-semver = { module = "io.github.z4kn4fein:semver", version.ref = "kotlinSemver" }
jreleaser = { module = "org.jreleaser:jreleaser-gradle-plugin", version.ref = "jreleaserPlugin" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidatorPlugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaserPlugin" }
power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
xemantic-conventions = { id = "com.xemantic.gradle.xemantic-conventions", version.ref = "xemanticConventionsPlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }
