# Builds the release
name: Build release

on:
  release:
    types: [ published ]

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout sources
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.0

      - name: Build
        env:
          ORG_GRADLE_PROJECT_githubActor: ${{ secrets.GITHUBACTOR }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUBTOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          JRELEASER_DISCORD_WEBHOOK: ${{ secrets.DISCORD_ANNOUCEMENTS_WEBHOOK }}
          JRELEASER_LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          #          in the future, once https://github.com/jreleaser/jreleaser/issues/1796 is fix, it should be xemantic page on LinkedIn, right now the owner is taken from the profile
          #          JRELEASER_LINKEDIN_OWNER: ${{ secrets.LINKEDIN_OWNER }}
          JRELEASER_BLUESKY_HOST: ${{ vars.BLUESKY_HOST }}
          JRELEASER_BLUESKY_HANDLE: ${{ vars.BLUESKY_HANDLE }}
          JRELEASER_BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

        run: ./gradlew -Pversion=$VERSION build sourcesJar signPluginMavenPublication publish jreleaserFullRelease

      - name: Display JReleaser trace.log
        run: |
          if [ -f build/jreleaser/trace.log ]; then
            echo "trace.log Content:"
            cat build/jreleaser/trace.log
          else
            echo "trace.log file not found"
          fi
